### ISSUE TITLE
facing the same issue of #48

### ISSUE THREAD

**Issue by myinnos** [SchibstedSpain/Leku#53] opened 2017-01-21 08:18 UTC
#48 

Am facing with same issue with Activity!
`java.lang.NoSuchMethodError: No static method create(Lrx/Observable$OnSubscribe;)Lrx/Observable; in class Lrx/Observable; or its super classes (declaration of 'rx.Observable' appears in /data/data/in.pnplabs.babyonboard/files/instant-run/dex/slice-slice_6-classes.dex)`
Let me know the solution!

**Comment by ferranpons** [comment] 2017-01-25 12:03
Hi @myinnos 

Your issue looks similar to one I faced some time ago related to an issue with the version of JDK. Or if you use a newer version of RxJava (>= 1.2.4) in your app this could happen. Anyway please provide more info about how do you use the library to try to understand the issue and reproduce it.

- Which version of JDK do you use?
- Do you use in your app RxJava/RxAndroid? And which version?
- Which version of the library do you actually use?
- Do you have the localization permission granted?
- Are you sending to the activity parameters through the bundle?
- Could you describe what are the actions do you make to raise that error?
- Android monitor shows any log related to the library when the error is shown?
- Any other thing that could help me to reproduce the error?


Many thanks

**Comment by ferranpons** [comment] 2017-02-10 12:43
Sorry @myinnos but I'm closing the issue because I have not received any answer from you in 2 weeks. If you still experience the issue feel free to reopen it and give me more info to try to reproduce the error.

**Closed by ferranpons** 2017-02-10 12:43 UTC
Labels: bug, help wanted, needs verification
