### ISSUE TITLE
Searchview autocomplete not working

### ISSUE THREAD

**Issue by nambv** [SchibstedSpain/Leku#52] opened 2017-01-16 21:21 UTC
It's always return message:"There are no results for your search" and it's not display suggestion in searchview ,too

**Comment by ferranpons** [comment] 2017-01-17 06:53
Hi @nambv 

Please, could you give me more info about your issue? I need it to try to reproduce the error.

- Which version of the library do you actually use?
- Do you have the localization permission granted?
- Are you sending to the activity parameters through the bundle?
- Could you describe what are the actions do you make to raise that error?
- Android monitor shows any log related to the library when the error is shown?
- Any other thing that could help me to reproduce the error?

Many thanks!

**Comment by ferranpons** [comment] 2017-02-10 12:41
@nambv a new version is available with auto-complete for the search view (v3.0.0). Please check it out.

I'm closing the issue because you did not answer my questions in a reasonable timespan.

**Closed by ferranpons** 2017-02-10 12:41 UTC
Labels: bug, needs verification
