### ISSUE TITLE
Showing Error msg "Something went wrong. Please try again." on LocationPickerActivity on particular device 

### ISSUE THREAD

**Issue by jigs94** [SchibstedSpain/Leku#51] opened 2017-01-02 06:57 UTC
I have test on 5 device  , among that 3 device run successfully without any error ,but in 2 device get same error "Something went wrong. Please try again."

can you help me ?

**Comment by ferranpons** [comment] 2017-01-05 13:18
Hi @jigs94!

I need more info to try to know what's happening. Please, could provide which version of Android have the devices that were showing that error? Also, are showing logs related on the device monitor?

Many thanks

**Comment by jigs94** [comment] 2017-01-10 08:50
version is lollipop

**Comment by ferranpons** [comment] 2017-01-11 08:07
@jigs94 I'm sorry but with only that info is not enough for me to reproduce the problem. Please, could you give me more info?

- Which version of the library do you actually use?
- Do you have the localization permission granted?
- Are you sending to the activity parameters through the bundle?
- Could you describe what are the actions do you make to raise that error?
- Android monitor shows any log related to the library when the error is shown?
- Any other thing that could help me to reproduce the error?

Many thanks

**Comment by ferranpons** [comment] 2017-02-10 12:45
Sorry @jigs94 but I'm closing the issue because I have not received any answer from you in 1 month. If you still experience the issue feel free to re-open it and give me more info to try to reproduce the error.

**Closed by ferranpons** 2017-02-10 12:45 UTC
Labels: help wanted, needs verification

**Comment by MaxMello** [comment] 2017-02-10 22:10
Hello, I get the same error message as a Toast: "Something went wrong. Please try again." This equals the string key "load_location_error". I can start the intent. I can press the "GPS"-FAB to move to my current location. I can write into the Search bar and speak into the microphone. But: I don't have the Confirmation-FAB to actually get the chosen location and return to my previous activity. When typing into the Search bar, on every key press a new "Something went wrong. Please try again." spawns, as well as after finishing a voice input. If it put this into the intent:
`intent.putExtra(LocationPickerActivity.BACK_PRESSED_RETURN_OK, true);`
And I press back, it does NOT return OK, but instead RESULT_CANCELED.

My Google Developer Console shows the incoming requests for "Google Maps Android API", without any errors. 

Important parts of my AndroidMainfest.xml:
`      <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version"/>
        <meta-data
            android:name="com.google.android.maps.v2.API_KEY"
            android:value="@string/google_maps_key"/>
        <activity
            android:name="com.schibstedspain.leku.LocationPickerActivity"
            android:label="@string/title_activity_location_picker"
            android:parentActivityName=".view.activity.PreInfoActivity"
            android:theme="@style/AppTheme"
            android:windowSoftInputMode="adjustPan">
            <intent-filter>
                <action android:name="android.intent.action.SEARCH"/>
            </intent-filter>
            <meta-data
                android:name="android.app.searchable"
                android:resource="@xml/searchable"/>
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".view.activity.PreInfoActivity"/>
        </activity>
`
My module-level build.gradle:
`buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
repositories {
    maven { url 'https://maven.fabric.io/public' }
    jcenter()
}
android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'
    defaultConfig {
        applicationId "my.application.name.id"
        vectorDrawables.useSupportLibrary = true
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }
}
dependencies {
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.google.android.gms:play-services-auth:10.0.1'
    compile 'com.android.support:design:25.1.0'
    compile 'com.android.support:support-v4:25.1.0'
    compile 'com.android.support:cardview-v7:25.1.0'
    compile 'com.android.support:gridlayout-v7:25.1.0'
    compile 'com.android.support:support-vector-drawable:25.1.0'
    compile 'com.android.support:animated-vector-drawable:25.1.0'
    compile 'com.android.support:percent:25.1.0'
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.schibstedspain.android:leku:3.0.0' 
    [...]
}
apply plugin: 'com.google.gms.google-services'`
Screenshot:
![leku-screencap](https://cloud.githubusercontent.com/assets/6271594/22845866/f475bafa-efe4-11e6-9a7e-5273ddf076c6.png)

Devices: LG G3 (API 21) as well as Nexus 5X API 25 Emulator. 

Also, I don't really get how `SEARCH_ZONE` works exactly. If I don't pass it as an Extra, is this equal to a global search zone? And what exactly does the search zone do? I want the user to be able to choose a location globally.

I hope it is just a stupid, obvious mistake.
