### ISSUE TITLE
SearchView not working

### ISSUE THREAD

**Issue by tayorh27** [SchibstedSpain/Leku#66] opened 2017-03-01 10:42 UTC
It is not displaying any location option whenever i type a location.

**Comment by ferranpons** [comment] 2017-03-02 11:00
@tayorh27 I'm sorry but with only that info is not enough for me to reproduce the problem. Please, could you give me more info?

- Which version of the library do you actually use?
- Do you have the localization permission granted?
- Are you sending to the activity parameters through the bundle?
- Could you describe what are the actions do you make to raise that error?
- Android monitor shows any log related to the library when the error is shown?
- Any other thing that could help me to reproduce the error?

Many thanks

**Comment by tayorh27** [comment] 2017-03-02 11:07
I don't get errors at all. All permissions are granted. I'm using version
3.0.0.

The problem i have is that the searchView doesn't bring out suggestions
when i type which makes it difficult to select a location.

Also on the map, the marker pin is not moveable.

Therefore in general, I can't pick a location.

Also I'm not parsing any bundle to the activity.

Thanks for your assistance.

**Comment by ferranpons** [comment] 2017-03-09 09:11
@tayorh27 Which device are you using? If you try with another device is it working correctly?

**Comment by tayorh27** [comment] 2017-03-09 09:44
I'm using samsung note II with api 19. Is 3.0.0 ur latest version?

**Comment by ferranpons** [comment] 2017-03-09 11:45
Yes is the latest version. Please check if this is happening to you with other device. Anyway, I'll try to get a Samsung Note 2 with the same API to try to reproduce it. Thanks.

**Comment by ferranpons** [comment] 2017-03-09 12:20
@tayorh27 I've found a device that have the same issue. The problem is that the service is giving a timeout. But we tried with other apps that have google maps too and have the same problem. So we decided to reboot the device and now it's working perfect. If you haven't rebooted the device in a while please do it, It will work again.

Also, I tried with the same device you have with the same API version and it's working correctly.

¯\\\_(ツ)\_/¯

**Comment by tayorh27** [comment] 2017-03-09 12:29
Alright thank you very much for your assistance. Will try to do that and
get back to you. I love your library. It's awesome. Great job.

**Comment by ferranpons** [comment] 2017-03-09 13:40
![thanks](http://i.giphy.com/l0G192kSMLwTpO1CE.gif)

**Comment by ferranpons** [comment] 2017-03-20 14:42
@tayorh27 did you solve the issue? Can we close this issue?

**Comment by tayorh27** [comment] 2017-03-24 11:58
Yes you can close it.

Thanks.

**Closed** 2017-03-27 06:39 UTC
Labels: bug, help wanted, needs verification
